### ISSUE TITLE
cntrol+c复制一张jpg图片，然后进入markdown中cntrol+v，加载的小菊花一直在转，然后idea就卡死了

### ISSUE THREAD

**Issue by lushubei** [rocky-peng/PasteImageToMarkdown#7]
必现问题

另外默认上传的是png格式的，不好，我希望上传的事jpg格式，占用资源更小，方便网络加载

**Comment by rocky-peng** [comment]
收到，会尽快排查问题

**Comment by cayden-cheng** [comment]
> 必现问题
> 
> 另外一部分上传的是png格式的，不好，我希望上传的事jpg格式，占用资源更小，方便网络加载

**Comment by cayden-cheng** [comment]
请问你的idea版本是多少，另外插件版本是多少呢，这边测试没有问题，你是不是存本地呢

**Comment by lushubei** [comment]
idea 社区版 2019.3  版本
插件 1.5.9版本

刚才我将 之前的 Paste Image To Markdown 卸载之后，重启idea，现在问题已经不存在了，多谢各位积极响应
