### ISSUE TITLE
Local 端save出現問題

### ISSUE THREAD

**Issue by w22116972** [rocky-peng/PasteImageToMarkdown#9]
版本是2022.3.1

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/5381969/210128167-f8b2e6f8-d60c-4f62-ad04-f6f3f0f5c01a.png">

**Comment by rocky-peng** [comment]
你没有进行设置

**Comment by rocky-peng** [comment]
使用前要先填写相关信息
